spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://192.168.188.81:5236/SYSDBA?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: SYSDBA
    password: SYSDBA

  jpa:
    hibernate:
      ddl-auto: none # dm8与mysql ddl规则不一致，生成表策略在dm8不可用
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  rds:
    host: 58.213.45.42
    port: 16200
    password: 123